# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/90fb77ac-1f2e-4d8f-8fe5-01ce3ed9a300";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6410-04F0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/89335459-de62-4500-a808-2aea61682df3";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/89335459-de62-4500-a808-2aea61682df3";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/lib/libvirt" =
    { device = "/dev/disk/by-uuid/89335459-de62-4500-a808-2aea61682df3";
      fsType = "btrfs";
      options = [ "subvol=@varlibvirt" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/89335459-de62-4500-a808-2aea61682df3";
      fsType = "btrfs";
      options = [ "subvol=@varlibdocker" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5042f271-7b0a-4595-91ff-7fa309ed1fab"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
